task_2
romhik76/golang-one pull request #1
Opened 2021-11-22 13:04 UTC by romhik76

Никольский Роман

2021-11-23 18:33 UTC, v-lozhkin requested changes
Не увидел решения задачи #2

> 2. Напишите программу, вычисляющую диаметр и длину окружности по заданной площади круга. Площадь круга должна вводиться пользователем с клавиатуры.

2021-11-24 11:37 UTC, romhik76 commented
добавил второе задание

2021-11-24 11:43 UTC, v-lozhkin requested changes

2021-11-24 11:43 UTC, v-lozhkin commented on lesson2/calculator_circle.go
> +	const pi = 3.14
Готовая константа pi уже есть в пакете math

2021-11-24 11:43 UTC, v-lozhkin commented on lesson2/calculator_circle.go
> +	a := (s / pi) / (s / pi)
тут всегда получится единица. Формула некорректная

2021-11-24 13:48 UTC, romhik76 commented
исправил:
1.Готовая константа pi уже есть в пакете math
2.тут всегда получится единица. Формула некорректная

2021-11-24 19:51 UTC, v-lozhkin requested changes

2021-11-24 19:51 UTC, v-lozhkin commented on lesson2/calculator_circle.go
> +	d := math.Sqrt(s / math.Pi)
Это формула радиуса, а не диаметра

2021-11-25 06:07 UTC, romhik76 commented
исправил:
1. Это формула радиуса, а не диаметра

2021-11-25 08:09 UTC, v-lozhkin approved these changes
Супер! Можно мержить

2021-11-25 08:44 UTC, merged