task_3
romhik76/golang-one pull request #2
Opened 2021-11-22 13:31 UTC by romhik76

Никольский

2021-12-01 19:25 UTC, romhik76 commented
task_3 НЕВЕРНО

calculator ВЕРНО

2021-12-02 07:47 UTC, romhik76 commented
выполнил задание со звездочкой.
в калькуляторе так и не смог выполнить факториал

2021-12-02 18:48 UTC, v-lozhkin requested changes

2021-12-02 18:48 UTC, v-lozhkin commented on lesson3/number.go
> +		var flag = 0
флаг все же лучше хранить bool переменной

2021-12-02 18:48 UTC, v-lozhkin commented on lesson3/task_3.go
> +	case "^":
Если все же есть попробовать сделать факториал - то это достаточно просто. нужно запустить цикл от 2 до необходимого числа и перемножать

2021-12-02 18:48 UTC, v-lozhkin commented on lesson3/task_3.go
> +		if a == 0 || b == 0 {
Эта проверка должна быть до деления, иначе программа свалится еще раньше. 
И нельзя делить НА ноль, ноль на другое число делить можно

2021-12-03 06:13 UTC, romhik76 commented on lesson3/task_3.go
> +	case "^":
это понятно, я не пойму как это сделать для двух чисел, или как это сделать для одного из двух вводимых чисел

2021-12-03 07:40 UTC, romhik76 commented
исправил замечания!
выполнил калькулятор с функцией факториал но пришлось убрать возведение, пока что смог только так !

2021-12-03 12:14 UTC, romhik76 commented on lesson3/task_3.go
> +		if a == 0 || b == 0 {
исправил

2021-12-03 12:14 UTC, romhik76 commented on lesson3/task_3.go
> +	case "^":
сделал

2021-12-03 12:14 UTC, romhik76 commented on lesson3/number.go
> +		var flag = 0
исправил

2021-12-03 15:49 UTC, v-lozhkin commented on .idea/golang-one.iml
> +<?xml version="1.0" encoding="UTF-8"?>
Папку .idea надо удалить из гита

2021-12-04 13:27 UTC, v-lozhkin approved these changes
Принято, только удалите .idea

2021-12-05 14:37 UTC, merged