sorting
romhik76/golang-one pull request #4
Opened 2021-12-02 13:16 UTC by romhik76

Никольский

2021-12-02 18:56 UTC, v-lozhkin requested changes

2021-12-02 18:56 UTC, v-lozhkin commented on lesson4/task_4.go
> +		j := i
Зачем объявлять переменную итерирования до for? почему не объявить прямо внутри?

2021-12-05 14:38 UTC, romhik76 commented
что бы j была в области видимости для slice[j] = current

2021-12-05 14:38 UTC, romhik76 commented
я просто и так пробовал
for j := i; j > 0 && slice[j-1] > current; j--{
slice[j] = slice[j-1]
}

и так пробовал
for j := i; j > 0 && slice[j-1] > current; j-- {
slice[j] = slice[j-1]
slice[j] = current
}
}

вывод не корректный получается

2021-12-05 14:55 UTC, v-lozhkin approved these changes
Да, согласен. Сначала не заметил, прошу прощения. 
Более "гошная" реализация выглядит так
```go
for i := 1; i < len(slice); i++ {
		for j := i; j > 0 && slice[j-1] > slice[j]; j-- {
			slice[j], slice[j-1] = slice[j-1], slice[j]
		}
	}
```

Но ваш вариант тоже ок, принято.

2021-12-05 15:13 UTC, merged