fibonachi
romhik76/golang-one pull request #7
Opened 2021-12-06 15:57 UTC by romhik76

Никольский

2021-12-07 07:37 UTC, v-lozhkin requested changes

2021-12-07 07:37 UTC, v-lozhkin commented on lesson5/fibonachi.go
> +func fibonachi(n uint) uint {
Реализация верна, но оптимизирована (задание #2). Не хотите попробовать оптимизировать ?

2021-12-07 10:55 UTC, romhik76 commented
оптимизировал

2021-12-07 10:57 UTC, romhik76 commented
применил map

2021-12-07 13:21 UTC, romhik76 commented
v-lozhkin 6 hours ago
Реализация верна, но оптимизирована (задание #2). Не хотите попробовать оптимизировать ?

к сожалению я не совсем понял как это сделать!(((( пересмотрю урок и попробую сделать

2021-12-07 19:32 UTC, v-lozhkin approved these changes
Все верно вы оптимизировали

2021-12-08 06:47 UTC, romhik76 commented
можно мерджить?

2021-12-09 11:39 UTC, merged